language: java
sudo: required
jdk:
  - oraclejdk8
install: cd desapp-groupe-backend/ && mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 
script: mvn test -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
